// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3W3oGhiSIUV528UIGxMgBs_vAIfVXysc',
    appId: '1:781116536900:web:ed74eea05b98d331386411',
    messagingSenderId: '781116536900',
    projectId: 'stopalert-15716',
    authDomain: 'stopalert-15716.firebaseapp.com',
    storageBucket: 'stopalert-15716.firebasestorage.app',
    measurementId: 'G-M9PZJKEE5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYxFNAHOsRR4vqZkTrSmZhjburZjWV890',
    appId: '1:781116536900:android:3234b5a713a3ac41386411',
    messagingSenderId: '781116536900',
    projectId: 'stopalert-15716',
    storageBucket: 'stopalert-15716.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGLC4z9lYqqRoQ562JPsY8ewIq4aHV-jg',
    appId: '1:781116536900:ios:ba8574ca5f3d772a386411',
    messagingSenderId: '781116536900',
    projectId: 'stopalert-15716',
    storageBucket: 'stopalert-15716.firebasestorage.app',
    iosBundleId: 'com.originstudios.stopalert',
  );
}
